spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:bookings
    driver-class-name: org.h2.Driver
    username: root
    password: 12345
  flyway:
    enabled: true

token:
  signing:
    key: 8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb
  expirationInMillis: 1800000

data:
  seeding:
    enabled: true
    users:
      - email: user@hostfully.com
        firstName: User1
        lastName: User1
        password: pass
        role: ROLE_USER
      - email: owner@hostfully.com
        firstName: Owner1
        lastName: Owner1
        password: pass
        role: ROLE_OWNER